[project]
name = "simple-etl-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.4",
]


[dependency-groups]
dev = [
    "ruff>=0.12.0",
]

[tool.ruff]
lint.extend-select = ["N", "I", "E"]
line-length = 88
indent-width = 4

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"