[project]
name = "simple-etl-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[dependency-groups]
dev = [
    "requests>=2.32.4",
    "ruff>=0.12.0",
]

[tool-ruff]
lint.extend-select = ["N", "I", "E"]